services:
  - type: web
    name: google-books-search
    env: node
    buildCommand: npm install
    startCommand: npm start
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        value: process.env.MONGODB_URI
